//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_import

import 'package:one_of_serializer/any_of_serializer.dart';
import 'package:one_of_serializer/one_of_serializer.dart';
import 'package:built_collection/built_collection.dart';
import 'package:built_value/json_object.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';
import 'package:built_value/iso_8601_date_time_serializer.dart';
import 'package:utilities_dart_sdk_client/src/date_serializer.dart';
import 'package:utilities_dart_sdk_client/src/model/date.dart';

import 'package:utilities_dart_sdk_client/src/model/google_protobuf_well_known_types_any.dart';
import 'package:utilities_dart_sdk_client/src/model/google_rpc_status.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_address_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_address_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_alert_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_employee_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_employee_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_event_type_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_event_type_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_maintainer_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_maintainer_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_monitor_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_monitor_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_scenario_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_scenario_request_types_add_scenario_action_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_scenario_request_types_add_scenario_condition_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_add_scenario_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_address.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_alert.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_assign_unit_to_group_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_assign_unit_to_group_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_attach_device_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_attach_unit_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_build_report_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_change_user_role_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_confirm_otp_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_confirm_otp_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_connect_input_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_connect_input_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_contact.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_contact_type.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_create_group_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_create_group_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_create_share_link_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_create_share_link_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_dashboard_display_mode.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_delete_group_strategy.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_detach_user_from_unit_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_group.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_group_tree_node.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model_types_action.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model_types_command.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model_types_device_error.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model_types_device_manual.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model_types_lifecycle_event.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model_types_parameter.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model_types_sensor_connection.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model_types_trigger.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_device_model_types_unit.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_disable_scenario_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_disconnect_input_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_disconnect_input_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_dispatch_event_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_employee.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_enable_scenario_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_event.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_event_class.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_event_type.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_address_details_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_auth_method_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_company_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_device_models_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_device_models_request_types_model_version.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_device_models_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_device_static_map_url_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_distributions_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_distributions_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_distributions_response_types_distribution_entry.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_distributions_response_types_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_event_type_details_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_group_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_group_subtree_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_inputs_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_inputs_statistics_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_inputs_statistics_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_inputs_statistics_response_types_get_inputs_statistics_response_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_maintainer_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_monitor_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_notifications_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_profile_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_scenario_details_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_unit_group_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_unit_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_get_users_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_group_dashboard.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_hide_alert_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_hide_alert_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_importance.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_input.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_integration.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_integration_model.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_addresses_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_addresses_response_types_address_client.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_addresses_response_types_list_addresses_response_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_alerts_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_available_models_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_available_models_response_types_list_available_model_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_employees_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_event_types_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_events_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_group_units_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_groups_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_integartions_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_integration_models_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_monitors_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_roles_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_scenario_runs_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_scenarios_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_units_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_units_response_types_list_units_response_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_list_units_response_types_list_units_response_sensor.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_maintainer.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_maintenance_assignment.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_monitor.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_move_group_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_move_group_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_notification.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_refresh_token_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_refresh_token_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_request_password_reset_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_reset_client_address_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_reset_employee_password_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_reset_monitor_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_reset_password_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_reset_unit_group_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_reset_unit_group_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_role.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_run_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario_action.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario_action_argument.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario_action_type.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario_condition.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario_condition_operation.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario_condition_type.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario_run.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario_run_status.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_scenario_value_type.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_send_command_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_send_unit_ping_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_set_preferences_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_set_unit_parameter_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_show_alert_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_show_alert_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_sign_in_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_sign_in_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_start_scenario_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_unit.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_unit_command.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_unit_events_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_unit_events_response_types_event_property.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_unit_events_response_types_unit_property_changed_event.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_unit_model.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_unit_parameter.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_unit_status.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_address_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_client_address_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_company_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_contacts_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_employee_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_event_type_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_event_type_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_group_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_group_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_maintainer_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_maintenance_assignments_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_maintenance_assignments_request_types_update_maintenance_assignments_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_monitor_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_note_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_pinned_sensors_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_pinned_sensors_request_types_update_pinned_sensors_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_pinned_sensors_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_profile_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_scenario_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_scenario_request_types_update_scenario_action_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_scenario_request_types_update_scenario_condition_item.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_scenario_response.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_update_unit_firmware_request.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_user.dart';
import 'package:utilities_dart_sdk_client/src/model/utilities_web_api_protos_user_role.dart';

part 'serializers.g.dart';

@SerializersFor([
  GoogleProtobufWellKnownTypesAny,
  GoogleRpcStatus,
  UtilitiesWebApiProtosAddAddressRequest,
  UtilitiesWebApiProtosAddAddressResponse,
  UtilitiesWebApiProtosAddAlertRequest,
  UtilitiesWebApiProtosAddEmployeeRequest,
  UtilitiesWebApiProtosAddEmployeeResponse,
  UtilitiesWebApiProtosAddEventTypeRequest,
  UtilitiesWebApiProtosAddEventTypeResponse,
  UtilitiesWebApiProtosAddMaintainerRequest,
  UtilitiesWebApiProtosAddMaintainerResponse,
  UtilitiesWebApiProtosAddMonitorRequest,
  UtilitiesWebApiProtosAddMonitorResponse,
  UtilitiesWebApiProtosAddScenarioRequest,
  UtilitiesWebApiProtosAddScenarioRequestTypesAddScenarioActionItem,
  UtilitiesWebApiProtosAddScenarioRequestTypesAddScenarioConditionItem,
  UtilitiesWebApiProtosAddScenarioResponse,
  UtilitiesWebApiProtosAddress,
  UtilitiesWebApiProtosAlert,
  UtilitiesWebApiProtosAssignUnitToGroupRequest,
  UtilitiesWebApiProtosAssignUnitToGroupResponse,
  UtilitiesWebApiProtosAttachDeviceRequest,
  UtilitiesWebApiProtosAttachUnitRequest,
  UtilitiesWebApiProtosBuildReportRequest,
  UtilitiesWebApiProtosChangeUserRoleRequest,
  UtilitiesWebApiProtosConfirmOtpRequest,
  UtilitiesWebApiProtosConfirmOtpResponse,
  UtilitiesWebApiProtosConnectInputRequest,
  UtilitiesWebApiProtosConnectInputResponse,
  UtilitiesWebApiProtosContact,
  UtilitiesWebApiProtosContactType,
  UtilitiesWebApiProtosCreateGroupRequest,
  UtilitiesWebApiProtosCreateGroupResponse,
  UtilitiesWebApiProtosCreateShareLinkRequest,
  UtilitiesWebApiProtosCreateShareLinkResponse,
  UtilitiesWebApiProtosDashboardDisplayMode,
  UtilitiesWebApiProtosDeleteGroupStrategy,
  UtilitiesWebApiProtosDetachUserFromUnitRequest,
  UtilitiesWebApiProtosDeviceGroup,
  UtilitiesWebApiProtosDeviceGroupTreeNode,
  UtilitiesWebApiProtosDeviceModel,
  UtilitiesWebApiProtosDeviceModelTypesAction,
  UtilitiesWebApiProtosDeviceModelTypesCommand,
  UtilitiesWebApiProtosDeviceModelTypesDeviceError,
  UtilitiesWebApiProtosDeviceModelTypesDeviceManual,
  UtilitiesWebApiProtosDeviceModelTypesLifecycleEvent,
  UtilitiesWebApiProtosDeviceModelTypesParameter,
  UtilitiesWebApiProtosDeviceModelTypesSensorConnection,
  UtilitiesWebApiProtosDeviceModelTypesTrigger,
  UtilitiesWebApiProtosDeviceModelTypesUnit,
  UtilitiesWebApiProtosDisableScenarioRequest,
  UtilitiesWebApiProtosDisconnectInputRequest,
  UtilitiesWebApiProtosDisconnectInputResponse,
  UtilitiesWebApiProtosDispatchEventRequest,
  UtilitiesWebApiProtosEmployee,
  UtilitiesWebApiProtosEnableScenarioRequest,
  UtilitiesWebApiProtosEvent,
  UtilitiesWebApiProtosEventClass,
  UtilitiesWebApiProtosEventType,
  UtilitiesWebApiProtosGetAddressDetailsResponse,
  UtilitiesWebApiProtosGetAuthMethodResponse,
  UtilitiesWebApiProtosGetCompanyResponse,
  UtilitiesWebApiProtosGetDeviceModelsRequest,
  UtilitiesWebApiProtosGetDeviceModelsRequestTypesModelVersion,
  UtilitiesWebApiProtosGetDeviceModelsResponse,
  UtilitiesWebApiProtosGetDeviceStaticMapUrlResponse,
  UtilitiesWebApiProtosGetDistributionsRequest,
  UtilitiesWebApiProtosGetDistributionsResponse,
  UtilitiesWebApiProtosGetDistributionsResponseTypesDistributionEntry,
  UtilitiesWebApiProtosGetDistributionsResponseTypesItem,
  UtilitiesWebApiProtosGetEventTypeDetailsResponse,
  UtilitiesWebApiProtosGetGroupResponse,
  UtilitiesWebApiProtosGetGroupSubtreeResponse,
  UtilitiesWebApiProtosGetInputsResponse,
  UtilitiesWebApiProtosGetInputsStatisticsRequest,
  UtilitiesWebApiProtosGetInputsStatisticsResponse,
  UtilitiesWebApiProtosGetInputsStatisticsResponseTypesGetInputsStatisticsResponseItem,
  UtilitiesWebApiProtosGetMaintainerResponse,
  UtilitiesWebApiProtosGetMonitorResponse,
  UtilitiesWebApiProtosGetNotificationsResponse,
  UtilitiesWebApiProtosGetProfileResponse,
  UtilitiesWebApiProtosGetScenarioDetailsResponse,
  UtilitiesWebApiProtosGetUnitGroupResponse,
  UtilitiesWebApiProtosGetUnitResponse,
  UtilitiesWebApiProtosGetUsersResponse,
  UtilitiesWebApiProtosGroupDashboard,
  UtilitiesWebApiProtosHideAlertRequest,
  UtilitiesWebApiProtosHideAlertResponse,
  UtilitiesWebApiProtosImportance,
  UtilitiesWebApiProtosInput,
  UtilitiesWebApiProtosIntegration,
  UtilitiesWebApiProtosIntegrationModel,
  UtilitiesWebApiProtosListAddressesResponse,
  UtilitiesWebApiProtosListAddressesResponseTypesAddressClient,
  UtilitiesWebApiProtosListAddressesResponseTypesListAddressesResponseItem,
  UtilitiesWebApiProtosListAlertsResponse,
  UtilitiesWebApiProtosListAvailableModelsResponse,
  UtilitiesWebApiProtosListAvailableModelsResponseTypesListAvailableModelItem,
  UtilitiesWebApiProtosListEmployeesResponse,
  UtilitiesWebApiProtosListEventTypesResponse,
  UtilitiesWebApiProtosListEventsResponse,
  UtilitiesWebApiProtosListGroupUnitsResponse,
  UtilitiesWebApiProtosListGroupsResponse,
  UtilitiesWebApiProtosListIntegartionsResponse,
  UtilitiesWebApiProtosListIntegrationModelsResponse,
  UtilitiesWebApiProtosListMonitorsResponse,
  UtilitiesWebApiProtosListRolesResponse,
  UtilitiesWebApiProtosListScenarioRunsResponse,
  UtilitiesWebApiProtosListScenariosResponse,
  UtilitiesWebApiProtosListUnitsResponse,
  UtilitiesWebApiProtosListUnitsResponseTypesListUnitsResponseItem,
  UtilitiesWebApiProtosListUnitsResponseTypesListUnitsResponseSensor,
  UtilitiesWebApiProtosMaintainer,
  UtilitiesWebApiProtosMaintenanceAssignment,
  UtilitiesWebApiProtosMonitor,
  UtilitiesWebApiProtosMoveGroupRequest,
  UtilitiesWebApiProtosMoveGroupResponse,
  UtilitiesWebApiProtosNotification,
  UtilitiesWebApiProtosRefreshTokenRequest,
  UtilitiesWebApiProtosRefreshTokenResponse,
  UtilitiesWebApiProtosRequestPasswordResetRequest,
  UtilitiesWebApiProtosResetClientAddressRequest,
  UtilitiesWebApiProtosResetEmployeePasswordRequest,
  UtilitiesWebApiProtosResetMonitorRequest,
  UtilitiesWebApiProtosResetPasswordRequest,
  UtilitiesWebApiProtosResetUnitGroupRequest,
  UtilitiesWebApiProtosResetUnitGroupResponse,
  UtilitiesWebApiProtosRole,
  UtilitiesWebApiProtosRunRequest,
  UtilitiesWebApiProtosScenario,
  UtilitiesWebApiProtosScenarioAction,
  UtilitiesWebApiProtosScenarioActionArgument,
  UtilitiesWebApiProtosScenarioActionType,
  UtilitiesWebApiProtosScenarioCondition,
  UtilitiesWebApiProtosScenarioConditionOperation,
  UtilitiesWebApiProtosScenarioConditionType,
  UtilitiesWebApiProtosScenarioRun,
  UtilitiesWebApiProtosScenarioRunStatus,
  UtilitiesWebApiProtosScenarioValueType,
  UtilitiesWebApiProtosSendCommandRequest,
  UtilitiesWebApiProtosSendUnitPingRequest,
  UtilitiesWebApiProtosSetPreferencesRequest,
  UtilitiesWebApiProtosSetUnitParameterRequest,
  UtilitiesWebApiProtosShowAlertRequest,
  UtilitiesWebApiProtosShowAlertResponse,
  UtilitiesWebApiProtosSignInRequest,
  UtilitiesWebApiProtosSignInResponse,
  UtilitiesWebApiProtosStartScenarioRequest,
  UtilitiesWebApiProtosUnit,
  UtilitiesWebApiProtosUnitCommand,
  UtilitiesWebApiProtosUnitEventsResponse,
  UtilitiesWebApiProtosUnitEventsResponseTypesEventProperty,
  UtilitiesWebApiProtosUnitEventsResponseTypesUnitPropertyChangedEvent,
  UtilitiesWebApiProtosUnitModel,
  UtilitiesWebApiProtosUnitParameter,
  UtilitiesWebApiProtosUnitStatus,
  UtilitiesWebApiProtosUpdateAddressRequest,
  UtilitiesWebApiProtosUpdateClientAddressRequest,
  UtilitiesWebApiProtosUpdateCompanyRequest,
  UtilitiesWebApiProtosUpdateContactsRequest,
  UtilitiesWebApiProtosUpdateEmployeeRequest,
  UtilitiesWebApiProtosUpdateEventTypeRequest,
  UtilitiesWebApiProtosUpdateEventTypeResponse,
  UtilitiesWebApiProtosUpdateGroupRequest,
  UtilitiesWebApiProtosUpdateGroupResponse,
  UtilitiesWebApiProtosUpdateMaintainerRequest,
  UtilitiesWebApiProtosUpdateMaintenanceAssignmentsRequest,
  UtilitiesWebApiProtosUpdateMaintenanceAssignmentsRequestTypesUpdateMaintenanceAssignmentsItem,
  UtilitiesWebApiProtosUpdateMonitorRequest,
  UtilitiesWebApiProtosUpdateNoteRequest,
  UtilitiesWebApiProtosUpdatePinnedSensorsRequest,
  UtilitiesWebApiProtosUpdatePinnedSensorsRequestTypesUpdatePinnedSensorsItem,
  UtilitiesWebApiProtosUpdatePinnedSensorsResponse,
  UtilitiesWebApiProtosUpdateProfileRequest,
  UtilitiesWebApiProtosUpdateScenarioRequest,
  UtilitiesWebApiProtosUpdateScenarioRequestTypesUpdateScenarioActionItem,
  UtilitiesWebApiProtosUpdateScenarioRequestTypesUpdateScenarioConditionItem,
  UtilitiesWebApiProtosUpdateScenarioResponse,
  UtilitiesWebApiProtosUpdateUnitFirmwareRequest,
  UtilitiesWebApiProtosUser,
  UtilitiesWebApiProtosUserRole,
])
Serializers serializers = (_$serializers.toBuilder()
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(UtilitiesWebApiProtosUnitStatus)]),
        () => ListBuilder<UtilitiesWebApiProtosUnitStatus>(),
      )
      ..addBuilderFactory(
        const FullType(BuiltList, [FullType(String)]),
        () => ListBuilder<String>(),
      )
      ..add(const OneOfSerializer())
      ..add(const AnyOfSerializer())
      ..add(const DateSerializer())
      ..add(Iso8601DateTimeSerializer()))
    .build();

Serializers standardSerializers =
    (serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();
