//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

library openapi.api;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:collection/collection.dart';
import 'package:http/http.dart';
import 'package:intl/intl.dart';
import 'package:meta/meta.dart';

part 'api_client.dart';
part 'api_helper.dart';
part 'api_exception.dart';
part 'auth/authentication.dart';
part 'auth/api_key_auth.dart';
part 'auth/oauth.dart';
part 'auth/http_basic_auth.dart';
part 'auth/http_bearer_auth.dart';

part 'api/addresses_service_api.dart';
part 'api/alerts_service_api.dart';
part 'api/command_runner_api.dart';
part 'api/employees_service_api.dart';
part 'api/event_types_service_api.dart';
part 'api/integrations_service_api.dart';
part 'api/maintainers_service_api.dart';
part 'api/models_service_api.dart';
part 'api/monitors_service_api.dart';
part 'api/profile_service_api.dart';
part 'api/reports_service_api.dart';
part 'api/roles_service_api.dart';
part 'api/scenarios_service_api.dart';
part 'api/statistics_service_api.dart';
part 'api/streams_service_api.dart';
part 'api/units_service_api.dart';
part 'api/users_service_api.dart';
part 'api/utilities_web_api_api.dart';

part 'model/google_protobuf_well_known_types_any.dart';
part 'model/google_rpc_status.dart';
part 'model/utilities_web_api_protos_add_address_request.dart';
part 'model/utilities_web_api_protos_add_address_response.dart';
part 'model/utilities_web_api_protos_add_alert_request.dart';
part 'model/utilities_web_api_protos_add_employee_request.dart';
part 'model/utilities_web_api_protos_add_employee_response.dart';
part 'model/utilities_web_api_protos_add_event_type_request.dart';
part 'model/utilities_web_api_protos_add_event_type_response.dart';
part 'model/utilities_web_api_protos_add_maintainer_request.dart';
part 'model/utilities_web_api_protos_add_maintainer_response.dart';
part 'model/utilities_web_api_protos_add_monitor_request.dart';
part 'model/utilities_web_api_protos_add_monitor_response.dart';
part 'model/utilities_web_api_protos_add_scenario_request.dart';
part 'model/utilities_web_api_protos_add_scenario_request_types_add_scenario_action_item.dart';
part 'model/utilities_web_api_protos_add_scenario_request_types_add_scenario_condition_item.dart';
part 'model/utilities_web_api_protos_add_scenario_response.dart';
part 'model/utilities_web_api_protos_address.dart';
part 'model/utilities_web_api_protos_alert.dart';
part 'model/utilities_web_api_protos_attach_device_request.dart';
part 'model/utilities_web_api_protos_attach_unit_request.dart';
part 'model/utilities_web_api_protos_build_report_request.dart';
part 'model/utilities_web_api_protos_change_user_role_request.dart';
part 'model/utilities_web_api_protos_confirm_otp_request.dart';
part 'model/utilities_web_api_protos_confirm_otp_response.dart';
part 'model/utilities_web_api_protos_connect_input_request.dart';
part 'model/utilities_web_api_protos_connect_input_response.dart';
part 'model/utilities_web_api_protos_contact.dart';
part 'model/utilities_web_api_protos_contact_type.dart';
part 'model/utilities_web_api_protos_create_share_link_request.dart';
part 'model/utilities_web_api_protos_create_share_link_response.dart';
part 'model/utilities_web_api_protos_dashboard_display_mode.dart';
part 'model/utilities_web_api_protos_detach_user_from_unit_request.dart';
part 'model/utilities_web_api_protos_device_model.dart';
part 'model/utilities_web_api_protos_device_model_types_action.dart';
part 'model/utilities_web_api_protos_device_model_types_command.dart';
part 'model/utilities_web_api_protos_device_model_types_device_error.dart';
part 'model/utilities_web_api_protos_device_model_types_device_manual.dart';
part 'model/utilities_web_api_protos_device_model_types_lifecycle_event.dart';
part 'model/utilities_web_api_protos_device_model_types_parameter.dart';
part 'model/utilities_web_api_protos_device_model_types_sensor_connection.dart';
part 'model/utilities_web_api_protos_device_model_types_trigger.dart';
part 'model/utilities_web_api_protos_device_model_types_unit.dart';
part 'model/utilities_web_api_protos_disable_scenario_request.dart';
part 'model/utilities_web_api_protos_disconnect_input_request.dart';
part 'model/utilities_web_api_protos_disconnect_input_response.dart';
part 'model/utilities_web_api_protos_dispatch_event_request.dart';
part 'model/utilities_web_api_protos_employee.dart';
part 'model/utilities_web_api_protos_enable_scenario_request.dart';
part 'model/utilities_web_api_protos_event.dart';
part 'model/utilities_web_api_protos_event_class.dart';
part 'model/utilities_web_api_protos_event_type.dart';
part 'model/utilities_web_api_protos_get_address_details_response.dart';
part 'model/utilities_web_api_protos_get_auth_method_response.dart';
part 'model/utilities_web_api_protos_get_company_response.dart';
part 'model/utilities_web_api_protos_get_device_models_request.dart';
part 'model/utilities_web_api_protos_get_device_models_request_types_model_version.dart';
part 'model/utilities_web_api_protos_get_device_models_response.dart';
part 'model/utilities_web_api_protos_get_device_static_map_url_response.dart';
part 'model/utilities_web_api_protos_get_distributions_request.dart';
part 'model/utilities_web_api_protos_get_distributions_response.dart';
part 'model/utilities_web_api_protos_get_distributions_response_types_distribution_entry.dart';
part 'model/utilities_web_api_protos_get_distributions_response_types_item.dart';
part 'model/utilities_web_api_protos_get_event_type_details_response.dart';
part 'model/utilities_web_api_protos_get_inputs_response.dart';
part 'model/utilities_web_api_protos_get_inputs_statistics_request.dart';
part 'model/utilities_web_api_protos_get_inputs_statistics_response.dart';
part 'model/utilities_web_api_protos_get_inputs_statistics_response_types_get_inputs_statistics_response_item.dart';
part 'model/utilities_web_api_protos_get_maintainer_response.dart';
part 'model/utilities_web_api_protos_get_monitor_response.dart';
part 'model/utilities_web_api_protos_get_notifications_response.dart';
part 'model/utilities_web_api_protos_get_profile_response.dart';
part 'model/utilities_web_api_protos_get_scenario_details_response.dart';
part 'model/utilities_web_api_protos_get_unit_response.dart';
part 'model/utilities_web_api_protos_get_users_response.dart';
part 'model/utilities_web_api_protos_hide_alert_request.dart';
part 'model/utilities_web_api_protos_hide_alert_response.dart';
part 'model/utilities_web_api_protos_importance.dart';
part 'model/utilities_web_api_protos_input.dart';
part 'model/utilities_web_api_protos_integration.dart';
part 'model/utilities_web_api_protos_integration_model.dart';
part 'model/utilities_web_api_protos_list_addresses_response.dart';
part 'model/utilities_web_api_protos_list_addresses_response_types_address_client.dart';
part 'model/utilities_web_api_protos_list_addresses_response_types_list_addresses_response_item.dart';
part 'model/utilities_web_api_protos_list_alerts_response.dart';
part 'model/utilities_web_api_protos_list_available_models_response.dart';
part 'model/utilities_web_api_protos_list_available_models_response_types_list_available_model_item.dart';
part 'model/utilities_web_api_protos_list_employees_response.dart';
part 'model/utilities_web_api_protos_list_event_types_response.dart';
part 'model/utilities_web_api_protos_list_events_response.dart';
part 'model/utilities_web_api_protos_list_integartions_response.dart';
part 'model/utilities_web_api_protos_list_integration_models_response.dart';
part 'model/utilities_web_api_protos_list_monitors_response.dart';
part 'model/utilities_web_api_protos_list_roles_response.dart';
part 'model/utilities_web_api_protos_list_scenario_runs_response.dart';
part 'model/utilities_web_api_protos_list_scenarios_response.dart';
part 'model/utilities_web_api_protos_list_units_response.dart';
part 'model/utilities_web_api_protos_list_units_response_types_list_units_response_item.dart';
part 'model/utilities_web_api_protos_list_units_response_types_list_units_response_sensor.dart';
part 'model/utilities_web_api_protos_maintainer.dart';
part 'model/utilities_web_api_protos_maintenance_assignment.dart';
part 'model/utilities_web_api_protos_monitor.dart';
part 'model/utilities_web_api_protos_notification.dart';
part 'model/utilities_web_api_protos_refresh_token_request.dart';
part 'model/utilities_web_api_protos_refresh_token_response.dart';
part 'model/utilities_web_api_protos_request_password_reset_request.dart';
part 'model/utilities_web_api_protos_reset_client_address_request.dart';
part 'model/utilities_web_api_protos_reset_employee_password_request.dart';
part 'model/utilities_web_api_protos_reset_monitor_request.dart';
part 'model/utilities_web_api_protos_reset_password_request.dart';
part 'model/utilities_web_api_protos_role.dart';
part 'model/utilities_web_api_protos_run_request.dart';
part 'model/utilities_web_api_protos_scenario.dart';
part 'model/utilities_web_api_protos_scenario_action.dart';
part 'model/utilities_web_api_protos_scenario_action_argument.dart';
part 'model/utilities_web_api_protos_scenario_action_type.dart';
part 'model/utilities_web_api_protos_scenario_condition.dart';
part 'model/utilities_web_api_protos_scenario_condition_operation.dart';
part 'model/utilities_web_api_protos_scenario_condition_type.dart';
part 'model/utilities_web_api_protos_scenario_run.dart';
part 'model/utilities_web_api_protos_scenario_run_status.dart';
part 'model/utilities_web_api_protos_scenario_value_type.dart';
part 'model/utilities_web_api_protos_send_command_request.dart';
part 'model/utilities_web_api_protos_send_unit_ping_request.dart';
part 'model/utilities_web_api_protos_set_preferences_request.dart';
part 'model/utilities_web_api_protos_set_unit_parameter_request.dart';
part 'model/utilities_web_api_protos_show_alert_request.dart';
part 'model/utilities_web_api_protos_show_alert_response.dart';
part 'model/utilities_web_api_protos_sign_in_request.dart';
part 'model/utilities_web_api_protos_sign_in_response.dart';
part 'model/utilities_web_api_protos_start_scenario_request.dart';
part 'model/utilities_web_api_protos_unit.dart';
part 'model/utilities_web_api_protos_unit_command.dart';
part 'model/utilities_web_api_protos_unit_events_response.dart';
part 'model/utilities_web_api_protos_unit_events_response_types_event_property.dart';
part 'model/utilities_web_api_protos_unit_events_response_types_unit_property_changed_event.dart';
part 'model/utilities_web_api_protos_unit_model.dart';
part 'model/utilities_web_api_protos_unit_parameter.dart';
part 'model/utilities_web_api_protos_unit_status.dart';
part 'model/utilities_web_api_protos_update_address_request.dart';
part 'model/utilities_web_api_protos_update_client_address_request.dart';
part 'model/utilities_web_api_protos_update_company_request.dart';
part 'model/utilities_web_api_protos_update_contacts_request.dart';
part 'model/utilities_web_api_protos_update_employee_request.dart';
part 'model/utilities_web_api_protos_update_event_type_request.dart';
part 'model/utilities_web_api_protos_update_event_type_response.dart';
part 'model/utilities_web_api_protos_update_maintainer_request.dart';
part 'model/utilities_web_api_protos_update_maintenance_assignments_request.dart';
part 'model/utilities_web_api_protos_update_maintenance_assignments_request_types_update_maintenance_assignments_item.dart';
part 'model/utilities_web_api_protos_update_monitor_request.dart';
part 'model/utilities_web_api_protos_update_note_request.dart';
part 'model/utilities_web_api_protos_update_pinned_sensors_request.dart';
part 'model/utilities_web_api_protos_update_pinned_sensors_request_types_update_pinned_sensors_item.dart';
part 'model/utilities_web_api_protos_update_pinned_sensors_response.dart';
part 'model/utilities_web_api_protos_update_profile_request.dart';
part 'model/utilities_web_api_protos_update_scenario_request.dart';
part 'model/utilities_web_api_protos_update_scenario_request_types_update_scenario_action_item.dart';
part 'model/utilities_web_api_protos_update_scenario_request_types_update_scenario_condition_item.dart';
part 'model/utilities_web_api_protos_update_scenario_response.dart';
part 'model/utilities_web_api_protos_update_unit_firmware_request.dart';
part 'model/utilities_web_api_protos_user.dart';
part 'model/utilities_web_api_protos_user_role.dart';

/// An [ApiClient] instance that uses the default values obtained from
/// the OpenAPI specification file.
var defaultApiClient = ApiClient();

const _delimiters = {'csv': ',', 'ssv': ' ', 'tsv': '\t', 'pipes': '|'};
const _dateEpochMarker = 'epoch';
const _deepEquality = DeepCollectionEquality();
final _dateFormatter = DateFormat('yyyy-MM-dd');
final _regList = RegExp(r'^List<(.*)>$');
final _regSet = RegExp(r'^Set<(.*)>$');
final _regMap = RegExp(r'^Map<String,(.*)>$');

bool _isEpochMarker(String? pattern) =>
    pattern == _dateEpochMarker || pattern == '/$_dateEpochMarker/';
